import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect} from "react";
import fetchShopify from "shared/data/shopify/fetchShopify";
import {fetchCollectionByHandleQuery} from "shared/data/shopify/graphql/fetchCollectionByHandleQuery";
import fetchCollectionByHandle from "shared/data/shopify/fetchCollectionByHandle";
import { mapProduct } from "shared/utils/mapProduct";

const Home: NextPage = () => {

  useEffect(() => {
    fetchCollectionByHandle("all").then((data: any) => {
      console.log(data.products);
      // console.log(data.products.map(mapProduct));
    })

  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopstory demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://shopstory.app">Shopstory!</a>
        </h1>
      </main>

    </div>
  )
}



export default Home
